# Generated by Django 5.0.2 on 2024-02-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='title',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
